service: grocery-product-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: dotnet8
  region: us-east-1
  stage: dev

functions:
  api:
    handler: ProductManagement.API::ProductManagement.API.LambdaEntryPoint::FunctionHandlerAsync
    events:
      - httpApi: '*'

resources:
  Resources:
    ProductsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Products
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: Id
            AttributeType: S
        KeySchema:
          - AttributeName: Id
            KeyType: HASH

  Outputs:
    ApiUrl:
      Description: API Gateway endpoint URL
      Value:
        Fn::Sub: 'https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com'